idf_component_register(
    SRCS
        "main.c"
        "mks_servo42c.c"
        "servo_cmd.c"
        "servo_ctl.c"
        "console_serial.c"
        "console_tcp.c"
        "wifi_link.c"
        "diag.c"
    INCLUDE_DIRS
        "."
        "../include"
    REQUIRES
        driver
        esp_timer
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        lwip
)
